---
# System Identity
spire_owner: spire
spire_group: spire

# Standard Directory Structure
spire_dir_config: "/etc/spire/server"
spire_dir_data: "/opt/spire/server/data"

# Agent Side: Persisted Identity Directory
spire_agent_dir_data: "/opt/spire/agent/data"
