---
services:
  vault-server:
    image: docker.io/hashicorp/vault:2.0
    container_name: meta-provision-vault-server
    entrypoint: "vault"
    command: server -config=/opt/vault/vault.hcl
    volumes:
      - ./vault/vault.hcl:/opt/vault/vault.hcl:z
      - ./vault/data:/opt/vault/data:z
      - ./vault/tls:/opt/vault/tls:z
    user: "${HOST_UID}:${HOST_GID}"
    cap_add:
      - IPC_LOCK
    network_mode: "host"
    userns_mode: keep-id
    environment:
      - SKIP_SETCAP=true
      - VAULT_ADDR=https://127.0.0.1:8222
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "vault status -address=https://127.0.0.1:8222 -tls-skip-verify || if [ $? -eq 2 ]; then exit 0; else exit 1; fi",
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  gitlab-runner:
    image: docker.io/gitlab/gitlab-runner:v19.0.1
    container_name: gitlab-runner-csning1998-lab-shared
    network_mode: "host"
    restart: always
    security_opt:
      - label=disable
    volumes:
      - ./runner-config:/etc/gitlab-runner:z
      - /run/user/${HOST_UID}/podman/podman.sock:/run/podman/podman.sock:z
