---
base_baremetal_etcd_base:
  version: "v3.5.14"
  binary:
    url_base: "https://github.com/etcd-io/etcd/releases/download"
    install_path: "/usr/local/bin"
    files:
      - etcd
      - etcdctl

# Internal variables for download logic
_base_baremetal_etcd_archive_name: "etcd-{{ base_baremetal_etcd_base.version }}-linux-amd64.tar.gz"
_base_baremetal_etcd_release_url: "{{ base_baremetal_etcd_base.binary.url_base }}/{{ base_baremetal_etcd_base.version }}"
_base_baremetal_etcd_download_url: "{{ _base_baremetal_etcd_release_url }}/{{ _base_baremetal_etcd_archive_name }}"
_base_baremetal_etcd_temp_path: "/tmp/{{ _base_baremetal_etcd_archive_name }}"
_base_baremetal_etcd_temp_extract_path: "/tmp/etcd-{{ base_baremetal_etcd_base.version }}-linux-amd64"
