---
- name: Restart Vault Agent
  ansible.builtin.systemd:
    name: vault-agent
    state: restarted

- name: Restart spiffe-helper Container
  community.docker.docker_container:
    name: "{{ utils_vault_agent_helper_container_name }}"
    restart: true
