package hostsops

import (
	"context"
	"errors"
	"net/netip"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

const prefix = "meta-platform-"

// networkXML mirrors the dns element of virsh net-dumpxml for a network of the project.
const networkXML = `<network>
  <name>meta-platform-spire-child</name>
  <dns enable='yes'>
    <host ip='172.16.127.250'>
      <hostname>meta-platform-vault-downstream-frontend.production.homelab-infra.dev</hostname>
      <hostname>vault-downstream.production.homelab-infra.dev</hostname>
    </host>
    <host ip='172.16.128.250'>
      <hostname>harbor-origin.production.homelab-infra.dev</hostname>
      <hostname>meta-platform-harbor-origin-frontend.production.homelab-infra.dev</hostname>
    </host>
    <host ip='10.0.0.5'>
      <hostname>other-project-node.example.dev</hostname>
    </host>
  </dns>
</network>`

func mustParseAddr(t *testing.T, s string) netip.Addr {
	t.Helper()
	addr, err := netip.ParseAddr(s)
	if err != nil {
		t.Fatalf("parse %s: %v", s, err)
	}
	return addr
}

// assertRecords fails unless got equals want by address and by host names in order.
func assertRecords(t *testing.T, got, want []Record) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("records = %+v, want %+v", got, want)
	}
	for i := range got {
		if got[i].IP != want[i].IP || !slices.Equal(got[i].Hostnames, want[i].Hostnames) {
			t.Fatalf("record %d = %+v, want %+v", i, got[i], want[i])
		}
	}
}

func TestParseDNSRecords_FiltersByProjectPrefix(t *testing.T) {
	got, err := ParseDNSRecords(networkXML, prefix)
	if err != nil {
		t.Fatalf("ParseDNSRecords: %v", err)
	}
	assertRecords(t, got, []Record{
		{mustParseAddr(t, "172.16.127.250"), []string{
			"meta-platform-vault-downstream-frontend.production.homelab-infra.dev",
			"vault-downstream.production.homelab-infra.dev",
		}},
		{mustParseAddr(t, "172.16.128.250"), []string{
			"harbor-origin.production.homelab-infra.dev",
			"meta-platform-harbor-origin-frontend.production.homelab-infra.dev",
		}},
	})
}

func TestParseDNSRecords_ReturnsNoneWithoutProjectRecords(t *testing.T) {
	for name, xml := range map[string]string{
		"no dns element":    `<network><name>default</name></network>`,
		"empty dns":         `<network><dns enable='yes'/></network>`,
		"foreign host only": `<network><dns><host ip='10.0.0.5'><hostname>node.example.dev</hostname></host></dns></network>`,
	} {
		t.Run(name, func(t *testing.T) {
			got, err := ParseDNSRecords(xml, prefix)
			if err != nil || len(got) != 0 {
				t.Errorf("ParseDNSRecords = %+v, %v, want none and nil", got, err)
			}
		})
	}
}

func TestParseDNSRecords_RejectsMalformedInput(t *testing.T) {
	for name, c := range map[string]struct{ xml, want string }{
		"malformed xml":   {`<network><dns>`, "hostsops"},
		"invalid address": {`<network><dns><host ip='172.16.300.1'><hostname>meta-platform-x.dev</hostname></host></dns></network>`, "172.16.300.1"},
	} {
		t.Run(name, func(t *testing.T) {
			_, err := ParseDNSRecords(c.xml, prefix)
			if err == nil || !strings.Contains(err.Error(), c.want) {
				t.Errorf("ParseDNSRecords error = %v, want an error which contains %q", err, c.want)
			}
		})
	}
}

func TestMergeRecords_MergesAndSortsByAddress(t *testing.T) {
	vault := mustParseAddr(t, "172.16.127.250")
	low := mustParseAddr(t, "172.16.9.1")
	high := mustParseAddr(t, "172.16.10.1")

	got := MergeRecords(
		[]Record{{high, []string{"meta-platform-b.dev"}}, {vault, []string{"meta-platform-vault.dev", "vault.dev"}}},
		[]Record{{vault, []string{"meta-platform-vault.dev", "vault.dev"}}, {low, []string{"meta-platform-a.dev"}}},
		[]Record{{vault, []string{"vault.dev", "meta-platform-vault-alias.dev"}}},
	)
	assertRecords(t, got, []Record{
		{low, []string{"meta-platform-a.dev"}},
		{high, []string{"meta-platform-b.dev"}},
		{vault, []string{"meta-platform-vault.dev", "vault.dev", "meta-platform-vault-alias.dev"}},
	})
}

func TestMergeRecords_ReturnsEmptyWithoutInput(t *testing.T) {
	got := MergeRecords()
	if len(got) != 0 {
		t.Errorf("MergeRecords() = %+v, want none", got)
	}
}

func testRecords(t *testing.T) []Record {
	t.Helper()
	return []Record{
		{mustParseAddr(t, "172.16.125.250"), []string{"meta-platform-spire-parent.dev"}},
		{mustParseAddr(t, "172.16.127.250"), []string{"meta-platform-vault.dev", "vault.dev"}},
	}
}

// testBlock is the managed block which testRecords render.
const testBlock = BeginMark + "\n" +
	"172.16.125.250 meta-platform-spire-parent.dev\n" +
	"172.16.127.250 meta-platform-vault.dev vault.dev\n" +
	EndMark + "\n"

func TestRewriteHostsBlock_ReplacesOrAppendsManagedBlock(t *testing.T) {
	cases := []struct {
		name    string
		current string
		want    string
	}{
		{
			name: "block in the middle with the marker of the shell script",
			current: "127.0.0.1 localhost\n" +
				"# BEGIN meta-platform: generated by tools/sync-etc-hosts.sh from the libvirt DNS records\n" +
				"172.16.1.1 meta-platform-stale.dev\n" +
				EndMark + "\n" +
				"192.168.1.10 nas.home\n",
			want: "127.0.0.1 localhost\n" + testBlock + "192.168.1.10 nas.home\n",
		},
		{
			name:    "block absent",
			current: "127.0.0.1 localhost\n::1 localhost\n",
			want:    "127.0.0.1 localhost\n::1 localhost\n\n" + testBlock,
		},
		{
			name:    "block absent with trailing blank lines",
			current: "127.0.0.1 localhost\n\n\n",
			want:    "127.0.0.1 localhost\n\n" + testBlock,
		},
		{
			name:    "block absent without final newline",
			current: "127.0.0.1 localhost",
			want:    "127.0.0.1 localhost\n\n" + testBlock,
		},
		{
			name:    "empty file",
			current: "",
			want:    testBlock,
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, err := RewriteHostsBlock(c.current, testRecords(t))
			if err != nil {
				t.Fatalf("RewriteHostsBlock: %v", err)
			}
			if got != c.want {
				t.Errorf("RewriteHostsBlock =\n%s\nwant\n%s", got, c.want)
			}
			again, err := RewriteHostsBlock(got, testRecords(t))
			if err != nil || again != got {
				t.Errorf("second RewriteHostsBlock = %q, %v, want the first result unchanged", again, err)
			}
		})
	}
}

func TestRewriteHostsBlock_RejectsMalformedBlock(t *testing.T) {
	for name, current := range map[string]string{
		"begin without end": "127.0.0.1 localhost\n" + BeginMark + "\n172.16.1.1 meta-platform-x.dev\n192.168.1.10 nas.home\n",
		"end without begin": "127.0.0.1 localhost\n" + EndMark + "\n",
		"two blocks":        testBlock + "127.0.0.1 localhost\n" + testBlock,
		"nested begin":      BeginMark + "\n" + BeginMark + "\n" + EndMark + "\n",
	} {
		t.Run(name, func(t *testing.T) {
			_, err := RewriteHostsBlock(current, testRecords(t))
			if !errors.Is(err, ErrMalformedBlock) {
				t.Errorf("RewriteHostsBlock error = %v, want ErrMalformedBlock", err)
			}
		})
	}
}

// TestRewriteHostsBlock_RejectsEmptyRecords covers a libvirt outage, which MUST NOT empty the managed block.
func TestRewriteHostsBlock_RejectsEmptyRecords(t *testing.T) {
	_, err := RewriteHostsBlock("127.0.0.1 localhost\n"+testBlock, nil)
	if !errors.Is(err, ErrNoRecords) {
		t.Errorf("RewriteHostsBlock error = %v, want ErrNoRecords", err)
	}
}

func writeHostsFile(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "hosts")
	err := os.WriteFile(path, []byte(content), 0o644)
	if err != nil {
		t.Fatalf("write hosts file: %v", err)
	}
	return path
}

func TestDiffHosts_ReportsUnifiedDiff(t *testing.T) {
	path := writeHostsFile(t, "127.0.0.1 localhost\n172.16.1.1 meta-platform-old.dev\n")

	diff, changed, err := DiffHosts(context.Background(), path, "127.0.0.1 localhost\n172.16.1.1 meta-platform-new.dev\n")
	if err != nil || !changed {
		t.Fatalf("DiffHosts = %v, %v, want changed and nil", changed, err)
	}
	for _, line := range []string{"-172.16.1.1 meta-platform-old.dev", "+172.16.1.1 meta-platform-new.dev"} {
		if !strings.Contains(diff, line) {
			t.Errorf("DiffHosts diff =\n%s\nwant line %q", diff, line)
		}
	}
}

func TestDiffHosts_ReportsNoChange(t *testing.T) {
	content := "127.0.0.1 localhost\n"
	diff, changed, err := DiffHosts(context.Background(), writeHostsFile(t, content), content)
	if err != nil || changed || diff != "" {
		t.Errorf("DiffHosts = %q, %v, %v, want \"\", false, nil", diff, changed, err)
	}
}

func TestDiffHosts_RejectsMissingFile(t *testing.T) {
	_, _, err := DiffHosts(context.Background(), filepath.Join(t.TempDir(), "absent"), "x\n")
	if err == nil {
		t.Error("DiffHosts error = nil, want an error for an absent hosts file")
	}
}

// TestApplyHosts_PreservesInodeAndCreatesBackup covers the inode of /etc/hosts, which carries the SELinux label of the file.
func TestApplyHosts_PreservesInodeAndCreatesBackup(t *testing.T) {
	original := "127.0.0.1 localhost\n"
	candidate := original + "\n" + testBlock
	path := writeHostsFile(t, original)
	before, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat hosts file: %v", err)
	}

	err = ApplyHosts(context.Background(), Config{HostsFile: path}, candidate)
	if err != nil {
		t.Fatalf("ApplyHosts: %v", err)
	}
	assertFileContent(t, path, candidate)
	assertFileContent(t, path+".bak", original)
	after, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat hosts file: %v", err)
	}
	if !os.SameFile(before, after) {
		t.Error("ApplyHosts replaced the hosts file, want a write into the same inode")
	}
}

func TestApplyHosts_RunsEveryWriteThroughElevate(t *testing.T) {
	dir := t.TempDir()
	log := filepath.Join(dir, "elevate.log")
	elevate := filepath.Join(dir, "elevate")
	err := os.WriteFile(elevate, []byte("#!/bin/sh\necho \"$*\" >> \""+log+"\"\nexec \"$@\"\n"), 0o700)
	if err != nil {
		t.Fatalf("write fake elevate: %v", err)
	}
	path := writeHostsFile(t, "127.0.0.1 localhost\n")

	err = ApplyHosts(context.Background(), Config{HostsFile: path, Elevate: []string{elevate}}, testBlock)
	if err != nil {
		t.Fatalf("ApplyHosts: %v", err)
	}
	assertFileContent(t, log, "cp -p "+path+" "+path+".bak\ntee "+path+"\n")
	assertFileContent(t, path, testBlock)
}

func TestApplyHosts_PreservesFileWhenBackupFails(t *testing.T) {
	dir := t.TempDir()
	elevate := filepath.Join(dir, "elevate")
	err := os.WriteFile(elevate, []byte("#!/bin/sh\necho 'sudo: a password is required' >&2\nexit 1\n"), 0o700)
	if err != nil {
		t.Fatalf("write fake elevate: %v", err)
	}
	original := "127.0.0.1 localhost\n"
	path := writeHostsFile(t, original)

	err = ApplyHosts(context.Background(), Config{HostsFile: path, Elevate: []string{elevate}}, testBlock)
	if err == nil || !strings.Contains(err.Error(), "a password is required") {
		t.Errorf("ApplyHosts error = %v, want the stderr of the failed backup", err)
	}
	assertFileContent(t, path, original)
}

func assertFileContent(t *testing.T, path, want string) {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(got) != want {
		t.Errorf("%s =\n%s\nwant\n%s", filepath.Base(path), got, want)
	}
}

// syncConfig returns a SyncConfig of the hosts file at path whose networks return documents and listErr.
func syncConfig(path string, documents []string, listErr error) SyncConfig {
	return SyncConfig{
		Config:         Config{HostsFile: path},
		Prefix:         prefix,
		ListNetworkXML: func() ([]string, error) { return documents, listErr },
	}
}

// currentHostsFile returns a hosts file whose managed block already holds the records of networkXML.
func currentHostsFile(t *testing.T) string {
	t.Helper()
	records, err := ParseDNSRecords(networkXML, prefix)
	if err != nil {
		t.Fatalf("ParseDNSRecords: %v", err)
	}
	return "127.0.0.1 localhost\n\n" + renderBlock(MergeRecords(records))
}

func TestSync_RewritesManagedBlock(t *testing.T) {
	stale := "127.0.0.1 localhost\n\n" + BeginMark + "\n172.16.1.1 meta-platform-stale.dev\n" + EndMark + "\n"
	cases := []struct {
		name        string
		current     func(t *testing.T) string
		apply       bool
		wantChanged bool
		wantWritten bool
	}{
		{"dry run", func(*testing.T) string { return stale }, false, true, false},
		{"apply", func(*testing.T) string { return stale }, true, true, true},
		{"already current", currentHostsFile, true, false, false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			current := c.current(t)
			path := writeHostsFile(t, current)

			got, err := Sync(context.Background(), syncConfig(path, []string{networkXML, networkXML}, nil), c.apply)
			if err != nil || got.Changed != c.wantChanged {
				t.Fatalf("Sync = %+v, %v, want changed %v", got, err, c.wantChanged)
			}
			assertSyncOutcome(t, path, current, got, c.wantWritten)
		})
	}
}

// assertSyncOutcome fails unless the hosts file at path matches wantWritten and a change carries the stale line in its diff.
func assertSyncOutcome(t *testing.T, path, current string, got SyncResult, wantWritten bool) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read hosts file: %v", err)
	}
	isWritten := string(content) != current
	if isWritten != wantWritten {
		t.Errorf("hosts file written %v, want %v", isWritten, wantWritten)
	}
	if got.Changed && !strings.Contains(got.Diff, "-172.16.1.1 meta-platform-stale.dev") {
		t.Errorf("Sync diff = %q, want the stale line removed", got.Diff)
	}
}

func TestSync_FailsWithoutWritingFile(t *testing.T) {
	listFailure := errors.New("libvirt: connect to qemu:///system")
	cases := []struct {
		name      string
		documents []string
		listErr   error
		hostsFile string
		want      string
	}{
		{"libvirt failure", nil, listFailure, "", "qemu:///system"},
		{"malformed network", []string{"<network><dns>"}, nil, "", "parse network XML"},
		{"no records", []string{`<network><name>default</name></network>`}, nil, "", "no DNS record"},
		{"absent hosts file", []string{networkXML}, nil, "absent", "no such file"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			original := "127.0.0.1 localhost\n"
			path := writeHostsFile(t, original)
			if c.hostsFile != "" {
				path = filepath.Join(filepath.Dir(path), c.hostsFile)
			}
			_, err := Sync(context.Background(), syncConfig(path, c.documents, c.listErr), true)
			if err == nil || !strings.Contains(err.Error(), c.want) {
				t.Errorf("Sync error = %v, want an error which contains %q", err, c.want)
			}
			if c.hostsFile == "" {
				assertFileContent(t, path, original)
			}
		})
	}
}
