// Package hostsops rewrites the block of /etc/hosts which mirrors the Terraform-declared DNS records of the libvirt networks.
package hostsops

import (
	"bytes"
	"context"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"net/netip"
	"os"
	"os/exec"
	"slices"
	"strings"
)

const (
	// BeginMarkPrefix opens the managed block. A begin line carries a description after the prefix.
	BeginMarkPrefix = "# BEGIN meta-platform"
	// BeginMark is the begin line which a rewrite writes.
	BeginMark = BeginMarkPrefix + ": generated by platform hosts sync from the libvirt DNS records"
	// EndMark closes the managed block.
	EndMark = "# END meta-platform"
)

var (
	// ErrNoRecords reports libvirt networks without any DNS record of the project.
	ErrNoRecords = errors.New("hostsops: libvirt returned no DNS record of the project")
	// ErrMalformedBlock reports a hosts file whose managed block lacks its end or repeats.
	ErrMalformedBlock = errors.New("hostsops: the managed block of the hosts file is malformed")
)

// Record is one hosts line: an address and its host names in declaration order.
type Record struct {
	IP        netip.Addr
	Hostnames []string
}

// Config holds the hosts file and the command prefix which elevates the backup and the write.
type Config struct {
	HostsFile string
	Elevate   []string
}

// networkDNS holds the dns element of a virNetworkGetXMLDesc document.
type networkDNS struct {
	Hosts []struct {
		IP        string   `xml:"ip,attr"`
		Hostnames []string `xml:"hostname"`
	} `xml:"dns>host"`
}

// ParseDNSRecords returns the DNS host records of networkXML which carry a host name with prefix.
func ParseDNSRecords(networkXML, prefix string) ([]Record, error) {
	var parsed networkDNS
	err := xml.Unmarshal([]byte(networkXML), &parsed)
	if err != nil {
		return nil, fmt.Errorf("hostsops: parse network XML: %w", err)
	}

	var records []Record
	for _, host := range parsed.Hosts {
		hasPrefix := slices.ContainsFunc(host.Hostnames, func(name string) bool { return strings.HasPrefix(name, prefix) })
		if !hasPrefix {
			continue
		}
		addr, err := netip.ParseAddr(host.IP)
		if err != nil {
			return nil, fmt.Errorf("hostsops: host address %q: %w", host.IP, err)
		}
		records = append(records, Record{IP: addr, Hostnames: slices.Clone(host.Hostnames)})
	}
	return records, nil
}

// MergeRecords returns the records of every set ordered by address, one record per address.
// Every libvirt network carries the records of the whole project, hence the sets repeat each record.
func MergeRecords(sets ...[]Record) []Record {
	var merged []Record
	indexes := map[netip.Addr]int{}
	for _, set := range sets {
		for _, record := range set {
			i, exists := indexes[record.IP]
			if !exists {
				indexes[record.IP] = len(merged)
				merged = append(merged, Record{IP: record.IP})
				i = len(merged) - 1
			}
			for _, name := range record.Hostnames {
				if !slices.Contains(merged[i].Hostnames, name) {
					merged[i].Hostnames = append(merged[i].Hostnames, name)
				}
			}
		}
	}
	slices.SortFunc(merged, func(x, y Record) int { return x.IP.Compare(y.IP) })
	return merged
}

// RewriteHostsBlock returns current with the managed block replaced by records, or appended when absent.
// A malformed block fails the rewrite, since a guessed block boundary would drop lines of the operator.
func RewriteHostsBlock(current string, records []Record) (string, error) {
	if len(records) == 0 {
		return "", ErrNoRecords
	}
	block := renderBlock(records)

	lines := strings.SplitAfter(current, "\n")
	begin, end := -1, -1
	for i, line := range lines {
		line = strings.TrimSuffix(line, "\n")
		switch {
		case strings.HasPrefix(line, BeginMarkPrefix):
			if begin >= 0 {
				return "", fmt.Errorf("%w: a second begin line at line %d", ErrMalformedBlock, i+1)
			}
			begin = i
		case line == EndMark:
			if begin < 0 || end >= 0 {
				return "", fmt.Errorf("%w: an end line without a begin line at line %d", ErrMalformedBlock, i+1)
			}
			end = i
		}
	}
	if begin >= 0 && end < 0 {
		return "", fmt.Errorf("%w: the begin line at line %d has no end line", ErrMalformedBlock, begin+1)
	}

	if begin >= 0 {
		return strings.Join(lines[:begin], "") + block + strings.Join(lines[end+1:], ""), nil
	}
	rest := strings.TrimRight(current, "\n")
	if rest == "" {
		return block, nil
	}
	return rest + "\n\n" + block, nil
}

// renderBlock returns the managed block of records, one hosts line per record.
func renderBlock(records []Record) string {
	var b strings.Builder
	b.WriteString(BeginMark + "\n")
	for _, record := range records {
		b.WriteString(record.IP.String())
		b.WriteString(" ")
		b.WriteString(strings.Join(record.Hostnames, " "))
		b.WriteString("\n")
	}
	b.WriteString(EndMark + "\n")
	return b.String()
}

// DiffHosts returns the unified diff from the hosts file at path to candidate, and whether the two differ.
func DiffHosts(ctx context.Context, path, candidate string) (string, bool, error) {
	_, err := os.Stat(path)
	if err != nil {
		return "", false, fmt.Errorf("hostsops: %w", err)
	}

	var stdout, stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, "diff", "-u", "--label", path, "--label", path+" (candidate)", path, "-")
	cmd.Stdin = strings.NewReader(candidate)
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	err = cmd.Run()
	var exitErr *exec.ExitError
	switch {
	case err == nil:
		return "", false, nil
	case errors.As(err, &exitErr) && exitErr.ExitCode() == 1:
		return stdout.String(), true, nil
	default:
		return "", false, fmt.Errorf("hostsops: diff %s: %w: %s", path, err, strings.TrimSpace(stderr.String()))
	}
}

// ApplyHosts backs up cfg.HostsFile to cfg.HostsFile.bak and writes candidate in place through cfg.Elevate.
// The write through tee keeps the inode, hence the SELinux label of the hosts file.
func ApplyHosts(ctx context.Context, cfg Config, candidate string) error {
	err := runElevated(ctx, cfg.Elevate, nil, "cp", "-p", cfg.HostsFile, cfg.HostsFile+".bak")
	if err != nil {
		return err
	}
	return runElevated(ctx, cfg.Elevate, strings.NewReader(candidate), "tee", cfg.HostsFile)
}

// runElevated runs args behind the elevate prefix and reports the stderr of a failed run.
func runElevated(ctx context.Context, elevate []string, stdin io.Reader, args ...string) error {
	argv := append(slices.Clone(elevate), args...)
	var stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, argv[0], argv[1:]...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = stdin, io.Discard, &stderr
	err := cmd.Run()
	if err != nil {
		return fmt.Errorf("hostsops: %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(stderr.String()))
	}
	return nil
}
