---
- name: "Step 0. Log in to the Downstream Vault as the operator"
  ansible.builtin.include_role:
    name: utils_vault_operator_login
  vars:
    utils_vault_operator_login_wrapper: "{{ vault_operator_wrapper }}"
    utils_vault_operator_login_role: "{{ vault_operator_role }}"
    utils_vault_operator_login_auth_mount: "{{ vault_operator_mount }}"
    utils_vault_operator_login_endpoint: "{{ vault_endpoint }}"
    utils_vault_operator_login_ca_cert_path: "{{ vault_ca_cert_path }}"

- name: Step 1. Retrieve Harbor Robot credentials from Vault (Standard KV2)
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_endpoint }}"
    engine_mount_point: "secret"
    auth_method: "token"
    token: "{{ utils_vault_operator_login_token }}"
    path: "{{ harbor_robot_kv_path }}"
    validate_certs: true
    ca_cert: "{{ vault_ca_cert_path }}"
  register: provision_harbor_origin_harbor_credentials
  delegate_to: localhost
  become: false
  no_log: true

- name: Step 2. Verify Harbor OCI Login
  kubernetes.core.helm_registry_auth:
    host: "{{ harbor_registry }}"
    username: "{{ harbor_robot_user }}"
    password: "{{ provision_harbor_origin_harbor_credentials.secret.password_pusher }}"
  register: provision_harbor_origin_harbor_login
  no_log: true

- name: Step 3. Synchronize Helm Charts (Pull and Push)
  ansible.builtin.shell: |
    set -eo pipefail
    WORK_DIR=$(mktemp -d)
    trap 'rm -rf "$WORK_DIR"' EXIT
    cd "$WORK_DIR"

    {% set is_oci = item.is_oci | default(false) | bool %}

    {% if is_oci %}
    helm pull "{{ item.repo }}/{{ item.name }}" --version "{{ item.version }}"
    {% else %}
    helm pull "{{ item.name }}" --version "{{ item.version }}" --repo "{{ item.repo }}"
    {% endif %}

    helm push ./*.tgz "oci://{{ harbor_registry }}/{{ harbor_project }}"
  args:
    executable: /bin/bash
  loop: "{{ provision_harbor_origin_helm_charts_to_sync }}"
  register: provision_harbor_origin_sync_results
  changed_when: "'Pushed' in (provision_harbor_origin_sync_results.stderr | default(''))"
