---
# Keycloak
platform_keycloak_keycloak_image: "quay.io/keycloak/keycloak"
platform_keycloak_keycloak_version: "26.6.1"

# Postgres
platform_keycloak_postgres_image: "postgres"
platform_keycloak_postgres_version: "18-alpine"

# Operational Defaults
platform_keycloak_keycloak_static_route_metric: 100
