---
utils_spire_workload_entry_socket_path: "{{ spire_dir_data }}/private/api.sock"

# Duplicated from utils_spire_agent_join_token_vault_path, since role defaults do not
# carry across a separate include_role call.
utils_spire_workload_entry_join_token_vault_path: >-
  {{ vault_kv_namespace }}/spire-agent-join-token/{{ spire_cluster_name }}/{{
    inventory_hostname | regex_replace('^' ~ (spire_cluster_name | regex_escape) ~ '-', '') }}
