#!/usr/bin/env bash
# Rewrites the meta-platform block of /etc/hosts from the DNS records which Terraform writes into the libvirt networks.
# The default run prints the diff alone. Run with --apply under sudo to replace the block.
set -euo pipefail

HOSTS_FILE="${HOSTS_FILE:-/etc/hosts}"
LIBVIRT_URI="${LIBVIRT_URI:-qemu:///system}"
BEGIN_MARK="# BEGIN meta-platform: generated by tools/sync-etc-hosts.sh from the libvirt DNS records"
END_MARK="# END meta-platform"
# The block before the markers existed starts at this comment and runs to the end of the file.
LEGACY_MARK="# meta-platform: names follow the DNS records which Terraform writes into the libvirt networks."

APPLY=false
[ "${1:-}" = "--apply" ] && APPLY=true

records=$(
  for network in $(virsh -c "$LIBVIRT_URI" net-list --name); do
    virsh -c "$LIBVIRT_URI" net-dumpxml "$network" | python3 -c '
import sys, xml.etree.ElementTree as ET
root = ET.parse(sys.stdin).getroot()
# A record of meta-platform carries the cluster FQDN meta-platform-<service>-<component>, and records of other projects do not.
for host in root.findall("./dns/host"):
    names = [name.text for name in host.findall("hostname")]
    if any(name.startswith("meta-platform-") for name in names):
        print(host.get("ip"), " ".join(names))
'
  done | sort -t. -k1,1n -k2,2n -k3,3n -k4,4n -u
)
[ -n "$records" ] || { echo "sync-etc-hosts: libvirt returned no DNS record" >&2; exit 1; }

new_block=$(printf '%s\n%s\n%s\n' "$BEGIN_MARK" "$records" "$END_MARK")

# Keeps every line outside the meta-platform block, whether the file carries the markers or the legacy comment.
rest_file=$(mktemp)
trap 'rm -f "$rest_file"' EXIT
python3 - "$HOSTS_FILE" "$BEGIN_MARK" "$END_MARK" "$LEGACY_MARK" > "$rest_file" <<'PY'
import sys
path, begin, end, legacy = sys.argv[1:5]
lines = open(path).read().splitlines()
out, skipping = [], False
for line in lines:
    if line == begin or line == legacy:
        skipping = True
        continue
    if skipping and line == end:
        skipping = False
        continue
    if skipping and (line.startswith("172.") or line.strip() == ""):
        continue
    skipping = False
    out.append(line)
while out and out[-1].strip() == "":
    out.pop()
print("\n".join(out))
PY

candidate=$(printf '%s\n\n%s\n' "$(cat "$rest_file")" "$new_block")

if diff -u "$HOSTS_FILE" <(printf '%s\n' "$candidate") ; then
  echo "sync-etc-hosts: $HOSTS_FILE already matches the libvirt DNS records"
  exit 0
fi

if $APPLY; then
  [ "$(id -u)" -eq 0 ] || { echo "sync-etc-hosts: --apply MUST run under sudo" >&2; exit 1; }
  cp -p "$HOSTS_FILE" "${HOSTS_FILE}.bak"
  printf '%s\n' "$candidate" > "$HOSTS_FILE"
  echo "sync-etc-hosts: replaced the meta-platform block, backup at ${HOSTS_FILE}.bak"
fi
