---
# Section B: Configuration
shared_vault_vault_ui_enabled: true
shared_vault_vault_disable_mlock: true # Set to true to avoid memory locking issues

# Section C: Initialization
shared_vault_vault_init_key_shares: 1
shared_vault_vault_init_key_threshold: 1
shared_vault_vault_wait_delay_seconds: 10

# Section D: Unseal
shared_vault_vault_unseal_retries: 24
shared_vault_vault_unseal_delay_seconds: 5
